Changed case on "params.mainMenu" in config.toml to attempt to fix build Log from previous, failed build suggest this might be causing problems:
    Error: Error building site: failed to render pages: render of "page"
    failed: execute of template failed: template:
    _default/single.html:20:66: executing "bottom-menu" at <partial
    "bottom_menu.html" (dict "Page" . "show_back_menu_item" false)>:
    error calling partial:
    "/builds/mgrhm/mgrah.am/themes/sam/layouts/partials/bottom_menu.html:1:10":
    execute of template failed: template:
    partials/bottom_menu.html:1:10: executing
    "partials/bottom_menu.html" at <(.Page.Site.Params.mainMenu)
    (.show_back_menu_item)>: can't give argument to non-function
    .Page.Site.Params.mainMenu